### ISSUE TITLE
OSError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by lorelos** [CNES/Start-MAJA#41]
I installed MAJA on a virtualBox Xubuntu with shared windows  folders and I had an error when creating the symbolic link:

> Traceback (most recent call last):
  File "start_maja.py", line 662, in <module>
    start_maja(folder_file, gipp, lut, site, tile, orbit, nb_backward, options, debug_mode)
  File "start_maja.py", line 431, in start_maja
    add_config_files(repConf, repWork + "userconf")
  File "start_maja.py", line 186, in add_config_files
    os.symlink(repConf, repWorkConf)
OSError: [Errno 1] Operation not permitted

I solved it with a command on the windows host:
`C:\Program Files\Oracle\VirtualBox>VBoxManage setextradata oo_unix VBoxInternal2/SharedFoldersEnableSymlinksCreate/D_DRIVE 1`
and restarted VirtualBox.

**Comment by lorelos** [comment]
I solved it with a command on the windows host:
C:\Program Files\Oracle\VirtualBox>VBoxManage setextradata oo_unix VBoxInternal2/SharedFoldersEnableSymlinksCreate/D_DRIVE 1
and restarted VirtualBox.
