### ISSUE TITLE
OSError: [Errno 71] Protocol error

### ISSUE THREAD

**Issue by lorelos** [CNES/Start-MAJA#42]
I installed MAJA on a virtualBox Xubuntu with shared windows folders and I had an error when creating the symbolic link:

> Traceback (most recent call last):

File "start_maja.py", line 662, in
start_maja(folder_file, gipp, lut, site, tile, orbit, nb_backward, options, debug_mode)
File "start_maja.py", line 431, in start_maja
add_config_files(repConf, repWork + "userconf")
File "start_maja.py", line 186, in add_config_files
os.symlink(repConf, repWorkConf)
OSError: [Errno 71] Protocol error

I solved it ... **running virtualBox as an administrator**

**Comment by lorelos** [comment]
be careful, this workaround no longer works with version 6.1 of VirtualBox.
I had to downgrade to version 6.0.14
