### ISSUE TITLE
Bug handling missing SWBD files

### ISSUE THREAD

**Issue by grantpearse** [CNES/Start-MAJA#7]
Hi Oliver, thanks for looking at the SWBD issue.
The initial fix to handle SWBD files that are out of bounds (don't exits) worked to resolve the first issue extracting the SHP files but the **prepare_dtm.py** routine fails during gdal_rasterize. It looks like the unavailable SWBD files are added to the list populated in **170-188** of **tuilage_mnt_eau_S2.py** includes the unavailable files. Enumerating the list on **506** of lib_mnt.py triggers the error `print('missing SWBD watr file : ', [racine_nom_eau).]` during the gdal_rasterize phase.

The script I execute is on tile 60HXD:
`python Start-MAJA/prepare_dtm/DTMCreation.py -k Start-MAJA/prepare_dtm/S2Tiling.kml -g 60HXD -w Start-MAJA/prepare_dtm/Water/ -s Start-MAJA/prepare_dtm/SRTM/ -o Start-MAJA/prepare_dtm/DTM/60HXD
`
The results is:
```

> Found SRTM zip-archives...
> Found Water zip-archives...
> Processing with GranuleID
> 60HXD
> UTM60S
> 32760
> EPSG:32760
> 0
> 0
> 0
> 0
> 109800
> 109800
> 0
> 600000
> 5900020
> Working directory: /tmp/60HXDwj66g3zk
> Start-MAJA/prepare_dtm/SRTM/ /tmp/60HXDwj66g3zk Start-MAJA/prepare_dtm/Water/ /tmp/60HXDwj66g3zk
> [72, 20]
> [72, 20]
> (178.1244775712774, -37.040713289972636, 0.0) (179.38979675735044, -38.01144337672406, 0.0)
> [72, 20] [72, 20]
> ['srtm_72_20.tif']
> (178.1244775712774, -37.040713289972636, 0.0) (179.38979675735044, -38.01144337672406, 0.0)
> [178, -38] [179, -39]
> longitudes 178 179
> latitudes -39 -38
> center coordinates [[178.5, -38.5], [178.5, -37.5], [179.5, -38.5], [179.5, -37.5]]
> ['e178s39', 'e178s38', 'e179s39', 'e179s38']
> /tmp/60HXDwj66g3zk
> liste_fic_mnt ['srtm_72_20.tif']
> Archive:  Start-MAJA/prepare_dtm/Water/e178s39i.zip
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/e178s39i.dbf  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/e178s39i.shp  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/e178s39i.shx  
>    creating: /tmp/60HXDwj66g3zk/tmpbsclecsi/Documents/
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/Documents/Readme File SRTM Water Body Data.doc  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/Documents/SRTM Edit Rules v2.0 12 Mar 03.doc  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/Documents/SWBD Product Specific Guidance v2.0 12 Mar 03jas.doc  
> Archive:  Start-MAJA/prepare_dtm/Water/e178s38i.zip
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/e178s38i.dbf  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/e178s38i.shp  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/e178s38i.shx  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/Documents/Readme File SRTM Water Body Data.doc  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/Documents/SRTM Edit Rules v2.0 12 Mar 03.doc  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/Documents/SWBD Product Specific Guidance v2.0 12 Mar 03jas.doc  
> FIC: srtm_72_20.tif
> <class 'str'> <class 'str'>
> Start-MAJA/prepare_dtm/SRTM//srtm_72_20.tif
> Archive:  Start-MAJA/prepare_dtm/SRTM//srtm_72_20.zip
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/readme.txt  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/srtm_72_20.hdr  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/srtm_72_20.tfw  
>   inflating: /tmp/60HXDwj66g3zk/tmpbsclecsi/srtm_72_20.tif  
> gdalwarp  -r cubic -srcnodata -32767 -dstnodata 0  /tmp/60HXDwj66g3zk/tmpbsclecsi/srtm_72_20.tif /tmp/60HXDwj66g3zk/tmpbsclecsi/srtm_72_20nodata0.tif
> 
> Creating output file that is 6001P x 6001L.
> Processing input file /tmp/60HXDwj66g3zk/tmpbsclecsi/srtm_72_20.tif.
> 0...10...20...30...40...50...60...70...80...90...100 - done.
> e178s39
> #############Fichier eau : /tmp/60HXDwj66g3zk/tmpbsclecsi/e178s39i.shp
> gdal_rasterize -burn 1 -l e178s39i /tmp/60HXDwj66g3zk/tmpbsclecsi/e178s39i.shp /tmp/60HXDwj66g3zk/tmpbsclecsi/srtm_72_20_tmp.tif
> Warning 1: The output raster dataset has a SRS, but the input vector layer SRS is unknown.
> Ensure input vector has the same SRS, otherwise results might be incorrect.
> 0...10...20...30...40...50...60...70...80...90...100 - done.
> e178s38
> #############Fichier eau : /tmp/60HXDwj66g3zk/tmpbsclecsi/e178s38i.shp
> gdal_rasterize -burn 1 -l e178s38i /tmp/60HXDwj66g3zk/tmpbsclecsi/e178s38i.shp /tmp/60HXDwj66g3zk/tmpbsclecsi/srtm_72_20_tmp.tif
> Warning 1: The output raster dataset has a SRS, but the input vector layer SRS is unknown.
> Ensure input vector has the same SRS, otherwise results might be incorrect.
> 0...10...20...30...40...50...60...70...80...90...100 - done.
> e179s39
> missing SWBD watr file :  e179s39
> Traceback (most recent call last):
>   File "Start-MAJA/prepare_dtm/DTMCreation.py", line 326, in <module>
>     creator.run(args.out, args.tempout)
>   File "Start-MAJA/prepare_dtm/DTMCreation.py", line 286, in run
>     water_zipped = self.WaterZipped)
>   File "Start-MAJA/prepare_dtm/../prepare_dtm/tuilage_mnt_eau_S2.py", line 203, in run
>     calcul_masque_eau_mnt, working_dir=working_dir)
>   File "Start-MAJA/prepare_dtm/../prepare_dtm/lib_mnt.py", line 514, in fusion_mnt
>     land = TestLand(liste_centre_eau[i][0], liste_centre_eau[i][1])
>   File "Start-MAJA/prepare_dtm/../prepare_dtm/lib_mnt.py", line 57, in TestLand
>     layer = dataSource.GetLayer()
> AttributeError: 'NoneType' object has no attribute 'GetLayer'

```
Thanks

**Comment by olivierhagolle** [comment]
Hi Grant
did you clone the whole repository ?

The missing layer should be here (I hope...):
https://github.com/CNES/Start-MAJA/tree/master/prepare_dtm/land_polygons_osm
Best regards

**Comment by grantpearse** [comment]
Hi Olivier,
Thanks, I did clone the whole repo. It turns out is was a call in  lib_mnt.py that was the issue. It looks like it expected a path to the polygons relative to /prepare_dtm. I just ran the scripts I was making from this folder and it worked.
