### ISSUE TITLE
Seg. fault if processing is continued without backward init.

### ISSUE THREAD

**Issue by jprankl** [CNES/Start-MAJA#9]
Hi!

If I start Maja including the backward initialization it works fine. If the processing is continued it crashes.   
I think the reason is that L2type is overwritten when parsing the existing files, i.e. not specified for the processing later on.   
  line 382: L2type = Non   
should be moved before the loop (e.g. to line 372)  
Right?  

The original Maja output:

python ./start_maja.py -f folders.txt -c GIPP -t 33UWP -s 33UWP -d 20180701 -e 20180707 --debug -v
2019-04-04 10:11:53,536 - Start-Maja - INFO - repCAMS is missing from configuration file. Needed : repCode, repWork, repL1, repL2, repMaja
2019-04-04 10:11:53,536 - Start-Maja - INFO - Processing without CAMS

2019-04-04 10:11:53,560 - Start-Maja - INFO - Most recent processed date : 20180705
2019-04-04 10:11:53,560 - Start-Maja - INFO - => processing date 20180707
Traceback (most recent call last):
  File "./start_maja.py", line 637, in <module>
    start_maja(folder_file, context, site, tile, orbit, nb_backward, options, debug_mode)
  File "./start_maja.py", line 482, in start_maja
    logger.info("MAJA command failed : %s", commande)
UnboundLocalError: local variable 'commande' referenced before assignment

**Comment by olivierhagolle** [comment]
Thanks for the hint, works much better like that.
Olivier
